DROP TABLE catalogue;

CREATE TABLE catalogue (
	id serial PRIMARY KEY,
    vehicle_type varchar(50) NOT NULL,
    manufacturer varchar(150) NOT NULL,
    model varchar(150) NOT NULL,
   	vehicle_version varchar(150) NOT NULL,
    engine varchar(150) NULL,
	gearbox_chassis varchar(150) NULL,
    kw varchar(150) NULL,
    year_str varchar(150) NULL,
    kit varchar(150) NULL,
    code_1 varchar(150) NULL,
    code_2 varchar(150) NULL,
    code_3 varchar(150) NULL,
    zero varchar(150) NULL,
    z varchar(150) NULL,
    splines varchar(150) NULL,
    last_field varchar(150) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NULL
);

CREATE TABLE crossreferences (
	id serial PRIMARY KEY,
    notes varchar(200) NULL,
    type varchar(100) NULL,
    sassone_code varchar(100) NOT NULL,
   	cross1zf varchar(100) NULL,
   	cross2zf varchar(100) NULL,
   	cross3zf varchar(100) NULL,
   	cross4zf varchar(100) NULL,
   	cross5zf varchar(100) NULL,
   	cross6zf varchar(100) NULL,
   	cross1luk varchar(100) NULL,
   	cross2luk varchar(100) NULL,
   	cross3luk varchar(100) NULL,
   	cross4luk varchar(100) NULL,
   	cross5luk varchar(100) NULL,
   	cross6luk varchar(100) NULL,
   	cross7luk varchar(100) NULL,
    cross1valeo varchar(100) NULL,
    cross2valeo varchar(100) NULL,
    cross3valeo varchar(100) NULL,
    cross4valeo varchar(100) NULL,
    cross5valeo varchar(100) NULL,
    cross6valeo varchar(100) NULL,
    cross1oe varchar(100) NULL,
    cross2oe varchar(100) NULL,
    cross3oe varchar(100) NULL,
    cross4oe varchar(100) NULL,
    cross5oe varchar(100) NULL,
    cross6oe varchar(100) NULL,
    cross7oe varchar(100) NULL,
    cross8oe varchar(100) NULL,
    cross9oe varchar(100) NULL,
    cross10oe varchar(100) NULL
);